version: "0.4"

services:
  expo:
    build:
      context: ./expo-app
    image: ghcr.io/joaogw/guiaturistico/expo-app:latest
    ports:
      - "19000:19000" # Metro bundler
      - "19001:19001" # Tunnel
      - "19002:19002" # Web UI
    volumes:
      - ./expo-app:/app
    stdin_open: true
    tty: true

  nextjs:
    build:
      context: ./nextjs-api
    image: ghcr.io/joaogw/guiaturistico/nextjs-api:latest
    ports:
      - "3000:3000"
    volumes:
      - ./nextjs-api:/app
