FROM node:20-alpine

WORKDIR /app
RUN apk add --no-cache bash libc6-compat

COPY package*.json ./

RUN npm install -g expo
RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 19000 19001 19002

CMD sh -c "EXPO_NO_INTERACTIVE=true expo start --tunnel"