name: 'Guia Turistico EZTripAI - Docker Publish'

on:
  push:
    branches:
      - development

jobs:
  build-and-publish:
    name: 'Build and Publish Docker Images'
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and Push Expo Image
        uses: docker/build-push-action@v5
        with:
          context: ./expo-app
          file: ./expo-app/Docker/Dockerfile.dev
          push: true
          tags: ghcr.io/joaogw/guiaturistico/expo-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and Push Next.js Image
        uses: docker/build-push-action@v5
        with:
          context: ./nextjs-api
          file: ./nextjs-api/Docker/Dockerfile
          push: true
          tags: ghcr.io/joaogw/guiaturistico/nextjs-api:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max